import type { Product } from "../src/lib/types";

const IMG =
  "https://mriojdjmjciewgfimwzg.supabase.co/storage/v1/object/public/product-images";
const IMG_BASKETS = IMG;

export const seedProducts: Product[] = [
  // ---------------------------------------------------------------------------
  // Coffee — single origin & specialty
  // ---------------------------------------------------------------------------
  {
    id: "brazilian-santos",
    slug: "brazilian-santos",
    category: "coffee",
    name: { en: "Brazilian Santos", fr: "Santos du Brésil" },
    origin: { en: "Brazil · Santos", fr: "Brésil · Santos" },
    roast: "medium",
    tastingNotes: {
      en: ["Milk chocolate", "Roasted nut", "Low acidity"],
      fr: ["Chocolat au lait", "Noix grillée", "Faible acidité"],
    },
    description: {
      en: "Mild, sweet, and easygoing — the classic Brazilian cup. Smooth body, gentle acidity, and a nutty chocolate finish that works in espresso or drip.",
      fr: "Doux, sucré et facile à boire — la tasse brésilienne classique. Corps lisse, acidité douce et une finale de noisette et de chocolat, parfaite en espresso comme en filtre.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v1.jpg`,
    inStock: true,
  },
  {
    id: "burundi-aa",
    slug: "burundi-aa",
    category: "coffee",
    name: { en: "Burundi AA", fr: "Burundi AA" },
    origin: { en: "Burundi", fr: "Burundi" },
    roast: "medium",
    tastingNotes: {
      en: ["Blackcurrant", "Citrus", "Caramel"],
      fr: ["Cassis", "Agrumes", "Caramel"],
    },
    description: {
      en: "A bright, clean East African cup. Juicy acidity and berry sweetness over a tidy, balanced body.",
      fr: "Une tasse est-africaine vive et nette. Acidité juteuse et sucrosité de petits fruits sur un corps équilibré.",
    },
    priceCents: 2100,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v2.jpg`,
    inStock: true,
  },
  {
    id: "certified-fair-trade-organic",
    slug: "certified-fair-trade-organic",
    category: "coffee",
    name: {
      en: "Certified Fair Trade / Organic",
      fr: "Équitable / Biologique certifié",
    },
    origin: { en: "Fair Trade · Organic", fr: "Équitable · Biologique" },
    roast: "medium",
    tastingNotes: {
      en: ["Cocoa", "Toasted almond", "Brown sugar"],
      fr: ["Cacao", "Amande grillée", "Cassonade"],
    },
    description: {
      en: "Certified Fair Trade and organic, sourced responsibly and roasted to a balanced medium. A smooth, dependable everyday cup you can feel good about.",
      fr: "Certifié équitable et biologique, sourcé de façon responsable et torréfié en moyen équilibré. Une tasse quotidienne, douce et fiable, dont on peut être fier.",
    },
    priceCents: 2300,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v15.jpg`,
    inStock: true,
  },
  {
    id: "colombian-excelso",
    slug: "colombian-excelso",
    category: "coffee",
    name: { en: "Colombian Excelso", fr: "Colombien Excelso" },
    origin: { en: "Colombia", fr: "Colombie" },
    roast: "medium",
    tastingNotes: {
      en: ["Caramel", "Red apple", "Walnut"],
      fr: ["Caramel", "Pomme rouge", "Noix"],
    },
    description: {
      en: "The friendly face of Colombian coffee. Soft acidity, caramel sweetness, and a clean nutty finish — comfortable from the first sip.",
      fr: "Le visage aimable du café colombien. Acidité douce, sucrosité de caramel et finale nette de noix — réconfortant dès la première gorgée.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v3.jpg`,
    inStock: true,
  },
  {
    id: "colombian-supremo",
    slug: "colombian-supremo",
    category: "coffee",
    name: { en: "Colombian Supremo", fr: "Colombien Supremo" },
    origin: { en: "Colombia", fr: "Colombie" },
    roast: "medium",
    tastingNotes: {
      en: ["Brown sugar", "Cherry", "Hazelnut"],
      fr: ["Cassonade", "Cerise", "Noisette"],
    },
    description: {
      en: "Made from the largest, top-grade Colombian beans. Rounder and sweeter than Excelso, with a fuller body and a long, smooth finish.",
      fr: "Issu des plus gros grains colombiens de catégorie supérieure. Plus rond et plus sucré que l'Excelso, avec un corps plus ample et une longue finale soyeuse.",
    },
    priceCents: 2150,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v4.jpg`,
    inStock: true,
  },
  {
    id: "costa-rica-tarrazu",
    slug: "costa-rica-tarrazu",
    category: "coffee",
    name: { en: "Costa Rica Tarrazú", fr: "Costa Rica Tarrazú" },
    origin: { en: "Costa Rica · Tarrazú", fr: "Costa Rica · Tarrazú" },
    roast: "medium",
    tastingNotes: {
      en: ["Honey", "Orange", "Almond"],
      fr: ["Miel", "Orange", "Amande"],
    },
    description: {
      en: "From the high-altitude Tarrazú region. Crisp, clean, and brightly sweet, with a honeyed body and a citrus lift.",
      fr: "De la région d'altitude de Tarrazú. Net, propre et lumineusement sucré, avec un corps miellé et une touche d'agrumes.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v5.jpg`,
    inStock: true,
  },
  {
    id: "decaf-colombian",
    slug: "decaf-colombian",
    category: "coffee",
    name: { en: "Decaf Colombian", fr: "Colombien décaféiné" },
    origin: { en: "Colombia · Decaf", fr: "Colombie · Décaféiné" },
    roast: "medium",
    tastingNotes: {
      en: ["Caramel", "Cocoa", "Soft spice"],
      fr: ["Caramel", "Cacao", "Épices douces"],
    },
    description: {
      en: "All the comfort of Colombian coffee, none of the caffeine. Smooth, sweet, and satisfying — a cup you can enjoy any hour.",
      fr: "Tout le réconfort du café colombien, sans la caféine. Doux, sucré et satisfaisant — une tasse à savourer à toute heure.",
    },
    priceCents: 2200,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v7.jpg`,
    inStock: true,
  },
  {
    id: "espresso",
    slug: "espresso",
    category: "coffee",
    name: { en: "Espresso", fr: "Espresso" },
    origin: { en: "Espresso blend", fr: "Mélange espresso" },
    roast: "espresso",
    tastingNotes: {
      en: ["Dark chocolate", "Caramel", "Toasted nut"],
      fr: ["Chocolat noir", "Caramel", "Noix grillée"],
    },
    description: {
      en: "Our straight-ahead espresso roast. Deep, dark, and syrupy with a thick crema and just enough sweetness to stand up to milk.",
      fr: "Notre torréfaction espresso classique. Profonde, foncée et sirupeuse, avec une crema épaisse et juste assez de sucrosité pour tenir tête au lait.",
    },
    priceCents: 2150,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v6.jpg`,
    inStock: true,
  },
  {
    id: "guatemalan",
    slug: "guatemalan",
    category: "coffee",
    name: { en: "Guatemalan", fr: "Guatémaltèque" },
    origin: { en: "Guatemala", fr: "Guatemala" },
    roast: "medium",
    tastingNotes: {
      en: ["Milk chocolate", "Orange", "Toffee"],
      fr: ["Chocolat au lait", "Orange", "Caramel anglais"],
    },
    description: {
      en: "Grown in rich volcanic soil. Balanced and elegant, with cocoa depth, a touch of citrus, and a smooth toffee finish.",
      fr: "Cultivé dans un riche sol volcanique. Équilibré et élégant, avec une profondeur de cacao, une touche d'agrumes et une finale soyeuse de caramel.",
    },
    priceCents: 2200,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v8.jpg`,
    inStock: true,
  },
  {
    id: "java",
    slug: "java",
    category: "coffee",
    name: { en: "Java", fr: "Java" },
    origin: { en: "Indonesia · Java", fr: "Indonésie · Java" },
    roast: "dark",
    tastingNotes: {
      en: ["Dark chocolate", "Cedar", "Molasses"],
      fr: ["Chocolat noir", "Cèdre", "Mélasse"],
    },
    description: {
      en: "A full-bodied Indonesian classic, roasted dark. Low acidity, heavy body, and earthy, spicy depth that lingers.",
      fr: "Un classique indonésien corsé, torréfié foncé. Faible acidité, corps lourd et une profondeur terreuse et épicée qui persiste.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v9.jpg`,
    inStock: true,
  },
  {
    id: "kenya-aa",
    slug: "kenya-aa",
    category: "coffee",
    name: { en: "Kenya AA", fr: "Kenya AA" },
    origin: { en: "Kenya", fr: "Kenya" },
    roast: "medium",
    tastingNotes: {
      en: ["Blackcurrant", "Grapefruit", "Cane sugar"],
      fr: ["Cassis", "Pamplemousse", "Sucre de canne"],
    },
    description: {
      en: "The top grade of Kenyan coffee, and one of the brightest cups in the world. Bold blackcurrant and grapefruit acidity over a juicy, structured body.",
      fr: "La catégorie supérieure du café kényan, et l'une des tasses les plus vives au monde. Acidité audacieuse de cassis et de pamplemousse sur un corps juteux et structuré.",
    },
    priceCents: 2250,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v10.jpg`,
    featured: true,
    inStock: true,
  },
  {
    id: "mexican",
    slug: "mexican",
    category: "coffee",
    name: { en: "Mexican", fr: "Mexicain" },
    origin: { en: "Mexico", fr: "Mexique" },
    roast: "medium",
    tastingNotes: {
      en: ["Toasted almond", "Cocoa", "Light caramel"],
      fr: ["Amande grillée", "Cacao", "Caramel léger"],
    },
    description: {
      en: "Mellow and clean, with gentle acidity and a soft nutty sweetness. An easy drinker and a lovely lighter afternoon cup.",
      fr: "Doux et net, avec une acidité légère et une tendre sucrosité de noix. Facile à boire et idéal comme tasse d'après-midi plus légère.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v14.jpg`,
    inStock: true,
  },
  {
    id: "mocha",
    slug: "mocha",
    category: "coffee",
    name: { en: "Mocha", fr: "Moka" },
    origin: { en: "Yemen · Ethiopia", fr: "Yémen · Éthiopie" },
    roast: "medium",
    tastingNotes: {
      en: ["Cocoa", "Dried fruit", "Wine"],
      fr: ["Cacao", "Fruits séchés", "Vin"],
    },
    description: {
      en: "The original 'mocha' — named for the port of Mokha, with the natural cocoa and winey, dried-fruit character that gave chocolate-coffee its name.",
      fr: "Le « moka » original — nommé d'après le port de Mokha, avec ses notes naturelles de cacao et de fruits séchés vineux qui ont donné son nom au chocolat-café.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v16.jpg`,
    inStock: true,
  },
  {
    id: "jamaican-blue-mountain",
    slug: "jamaican-blue-mountain",
    category: "coffee",
    name: {
      en: "Pure Jamaican Blue Mountain",
      fr: "Pur Blue Mountain de Jamaïque",
    },
    origin: { en: "Jamaica · Blue Mountain", fr: "Jamaïque · Blue Mountain" },
    roast: "medium",
    tastingNotes: {
      en: ["Mild", "Sweet", "Silky"],
      fr: ["Doux", "Sucré", "Soyeux"],
    },
    description: {
      en: "One of the world's most sought-after coffees. Exceptionally smooth and refined — mild, sweet, and clean, with no bitterness and a silky finish.",
      fr: "L'un des cafés les plus recherchés au monde. Exceptionnellement lisse et raffiné — doux, sucré et net, sans amertume, avec une finale soyeuse.",
    },
    priceCents: 2450,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v19.jpg`,
    featured: true,
    inStock: true,
  },
  {
    id: "sumatra",
    slug: "sumatra",
    category: "coffee",
    name: { en: "Sumatra", fr: "Sumatra" },
    origin: { en: "Indonesia · Sumatra", fr: "Indonésie · Sumatra" },
    roast: "dark",
    tastingNotes: {
      en: ["Cedar", "Dark chocolate", "Earth"],
      fr: ["Cèdre", "Chocolat noir", "Terre"],
    },
    description: {
      en: "Wet-hulled in the Indonesian tradition and roasted dark. Big, heavy body with earthy, herbal depth and almost no acidity.",
      fr: "Dépulpé à l'humide selon la tradition indonésienne et torréfié foncé. Corps imposant et lourd, profondeur terreuse et herbacée, presque sans acidité.",
    },
    priceCents: 2250,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v17.jpg`,
    inStock: true,
  },
  {
    id: "swiss-water-decaf",
    slug: "swiss-water-decaf",
    category: "coffee",
    name: { en: "Swiss Water Process Decaf", fr: "Décaféiné Swiss Water" },
    origin: {
      en: "Decaf · Swiss Water Process",
      fr: "Décaféiné · Procédé Swiss Water",
    },
    roast: "medium",
    tastingNotes: {
      en: ["Cocoa", "Caramel", "Toasted nut"],
      fr: ["Cacao", "Caramel", "Noix grillée"],
    },
    description: {
      en: "Decaffeinated with the chemical-free Swiss Water Process, so the flavour stays intact. Smooth, sweet, and full — decaf with nothing to apologize for.",
      fr: "Décaféiné par le procédé Swiss Water sans produits chimiques, pour préserver toute la saveur. Doux, sucré et ample — un décaféiné sans compromis.",
    },
    priceCents: 2400,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v11-1.jpg`,
    inStock: true,
  },
  {
    id: "yirgacheffe",
    slug: "yirgacheffe",
    category: "coffee",
    name: { en: "Yirgacheffe", fr: "Yirgacheffe" },
    origin: { en: "Ethiopia · Yirgacheffe", fr: "Éthiopie · Yirgacheffe" },
    roast: "light",
    tastingNotes: {
      en: ["Jasmine", "Lemon", "Honey"],
      fr: ["Jasmin", "Citron", "Miel"],
    },
    description: {
      en: "The benchmark for floral Ethiopian coffee. Delicate and tea-like, with jasmine aromatics, bright citrus, and a clean honeyed sweetness.",
      fr: "La référence du café éthiopien floral. Délicat et proche du thé, avec des arômes de jasmin, des agrumes lumineux et une sucrosité miellée et nette.",
    },
    priceCents: 2250,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v13.jpg`,
    featured: true,
    inStock: true,
  },
  {
    id: "single-serve-pods",
    slug: "single-serve-pods",
    category: "coffee",
    name: { en: "Single-Serve Pods", fr: "Capsules à usage unique" },
    roast: "medium",
    description: {
      en: "Your favourite Café Gourmet coffee, packed into single-serve pods for the days you want a great cup without the ritual. Compatible with standard single-serve brewers.",
      fr: "Votre café Café Gourmet préféré, en capsules à usage unique pour les jours où l'on veut une bonne tasse sans le rituel. Compatible avec les machines à capsules standards.",
    },
    priceCents: 3000,
    imageUrl: `${IMG}/KCups.jpg`,
    inStock: true,
  },

  // ---------------------------------------------------------------------------
  // Coffee — signature blends
  // ---------------------------------------------------------------------------
  {
    id: "aqua-santa",
    slug: "aqua-santa",
    category: "coffee",
    name: { en: "Aqua Santa", fr: "Aqua Santa" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "medium-dark",
    tastingNotes: {
      en: ["Dark chocolate", "Toasted nut", "Brown sugar"],
      fr: ["Chocolat noir", "Noix grillée", "Cassonade"],
    },
    description: {
      en: "A smooth, full-bodied house blend with deep cocoa sweetness. Comforting and rich, built for everyday drinking.",
      fr: "Un mélange maison lisse et corsé, à la profonde sucrosité de cacao. Réconfortant et riche, conçu pour tous les jours.",
    },
    priceCents: 2150,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v19-1.jpg`,
    inStock: true,
  },
  {
    id: "cafe-sierra",
    slug: "cafe-sierra",
    category: "coffee",
    name: { en: "Café Sierra", fr: "Café Sierra" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "medium",
    tastingNotes: {
      en: ["Caramel", "Almond", "Mild citrus"],
      fr: ["Caramel", "Amande", "Agrumes doux"],
    },
    description: {
      en: "A balanced, approachable blend with caramel sweetness and a clean, nutty finish. An easy daily cup.",
      fr: "Un mélange équilibré et accessible, à la sucrosité de caramel et à la finale nette de noix. Une tasse quotidienne facile.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v23.jpg`,
    inStock: true,
  },
  {
    id: "di-giorno-espresso",
    slug: "di-giorno-espresso",
    category: "coffee",
    name: { en: "Di Giorno Espresso", fr: "Espresso Di Giorno" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "espresso",
    tastingNotes: {
      en: ["Dark chocolate", "Caramel", "Hazelnut"],
      fr: ["Chocolat noir", "Caramel", "Noisette"],
    },
    description: {
      en: "Our Italian-style espresso blend. Dark, rich, and sweet with a heavy crema — made for milk drinks and strong mornings.",
      fr: "Notre mélange espresso à l'italienne. Foncé, riche et sucré, avec une crema généreuse — fait pour les boissons lactées et les matins costauds.",
    },
    priceCents: 2150,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v21.jpg`,
    inStock: true,
  },
  {
    id: "jesses-blend",
    slug: "jesses-blend",
    category: "coffee",
    name: { en: "Jesse's Blend", fr: "Mélange de Jesse" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "medium",
    tastingNotes: {
      en: ["Milk chocolate", "Brown sugar", "Roasted nut"],
      fr: ["Chocolat au lait", "Cassonade", "Noix grillée"],
    },
    description: {
      en: "A friendly, well-rounded house blend — smooth, sweet, and never bitter. The kind of cup the whole house agrees on.",
      fr: "Un mélange maison sympathique et bien équilibré — doux, sucré, jamais amer. Le genre de tasse qui met tout le monde d'accord.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v22.jpg`,
    inStock: true,
  },
  {
    id: "manoir",
    slug: "manoir",
    category: "coffee",
    name: { en: "Manoir", fr: "Manoir" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "medium-dark",
    tastingNotes: {
      en: ["Dark chocolate", "Toffee", "Spice"],
      fr: ["Chocolat noir", "Caramel anglais", "Épices"],
    },
    description: {
      en: "A refined, fuller-roast blend with toffee depth and a whisper of spice. Elegant black, rich with milk.",
      fr: "Un mélange raffiné, à torréfaction plus poussée, avec une profondeur de caramel et un soupçon d'épices. Élégant noir, riche avec du lait.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v16.jpg`,
    inStock: true,
  },
  {
    id: "renaissance",
    slug: "renaissance",
    category: "coffee",
    name: { en: "Renaissance", fr: "Renaissance" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "medium",
    tastingNotes: {
      en: ["Caramel", "Cocoa", "Orange"],
      fr: ["Caramel", "Cacao", "Orange"],
    },
    description: {
      en: "A bright yet balanced blend — caramel and cocoa lifted by a touch of citrus. Lively without being sharp.",
      fr: "Un mélange lumineux mais équilibré — caramel et cacao rehaussés d'une touche d'agrumes. Vif sans être tranchant.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v18.jpg`,
    inStock: true,
  },
  {
    id: "ritz-blend",
    slug: "ritz-blend",
    category: "coffee",
    name: { en: "Ritz Blend", fr: "Mélange Ritz" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "medium-dark",
    tastingNotes: {
      en: ["Dark chocolate", "Brown sugar", "Toasted nut"],
      fr: ["Chocolat noir", "Cassonade", "Noix grillée"],
    },
    description: {
      en: "A classic, full-bodied blend with rich chocolate sweetness. Smooth, satisfying, and built to impress.",
      fr: "Un mélange classique et corsé, à la riche sucrosité de chocolat. Doux, satisfaisant, fait pour impressionner.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/PicCommWeb1.jpg`,
    inStock: true,
  },
  {
    id: "royal-blend",
    slug: "royal-blend",
    category: "coffee",
    name: { en: "Royal Blend", fr: "Mélange Royal" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "medium-dark",
    tastingNotes: {
      en: ["Cocoa", "Caramel", "Roasted nut"],
      fr: ["Cacao", "Caramel", "Noix grillée"],
    },
    description: {
      en: "A smooth, dependable house blend with cocoa and caramel depth. An everyday classic that never lets you down.",
      fr: "Un mélange maison lisse et fiable, à la profondeur de cacao et de caramel. Un classique quotidien qui ne déçoit jamais.",
    },
    priceCents: 2075,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v1.jpg`,
    inStock: true,
  },
  {
    id: "triathlon",
    slug: "triathlon",
    category: "coffee",
    name: { en: "Triathlon", fr: "Triathlon" },
    origin: { en: "House blend", fr: "Mélange maison" },
    roast: "dark",
    tastingNotes: {
      en: ["Dark chocolate", "Molasses", "Smoke"],
      fr: ["Chocolat noir", "Mélasse", "Fumée"],
    },
    description: {
      en: "Our boldest blend — dark, intense, and full-bodied for those who like it strong. Heavy on cocoa and molasses, low on acidity.",
      fr: "Notre mélange le plus audacieux — foncé, intense et corsé pour ceux qui l'aiment fort. Généreux en cacao et en mélasse, faible en acidité.",
    },
    priceCents: 2150,
    weightGrams: 500,
    imageUrl: `${IMG}/Coffee_v25.jpg`,
    inStock: true,
  },

  // ---------------------------------------------------------------------------
  // Tea
  // ---------------------------------------------------------------------------
  {
    id: "assam-tarajulie",
    slug: "assam-tarajulie",
    category: "tea",
    name: { en: "Assam (Tarajulie)", fr: "Assam (Tarajulie)" },
    origin: { en: "India · Assam", fr: "Inde · Assam" },
    tastingNotes: {
      en: ["Malt", "Honey", "Brisk"],
      fr: ["Malt", "Miel", "Vif"],
    },
    description: {
      en: "A robust, malty Assam from the Tarajulie estate. Full-bodied and brisk, it takes milk beautifully — a proper morning black tea.",
      fr: "Un Assam robuste et malté du domaine Tarajulie. Corsé et vif, il accueille parfaitement le lait — un vrai thé noir du matin.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v1.jpg`,
    inStock: true,
  },
  {
    id: "chamomile-egyptian",
    slug: "chamomile-egyptian",
    category: "tea",
    name: { en: "Chamomile (Egyptian)", fr: "Camomille (Égypte)" },
    origin: { en: "Egypt", fr: "Égypte" },
    tastingNotes: {
      en: ["Apple", "Honey", "Floral"],
      fr: ["Pomme", "Miel", "Floral"],
    },
    description: {
      en: "Soft, golden Egyptian chamomile flowers. Naturally caffeine-free, with gentle apple-honey sweetness — calm in a cup.",
      fr: "Douces fleurs de camomille d'Égypte aux reflets dorés. Naturellement sans caféine, avec une douce sucrosité de pomme et de miel — le calme en tasse.",
    },
    priceCents: 1350,
    imageUrl: `${IMG}/Tea_v13.jpg`,
    inStock: true,
  },
  {
    id: "ceylon-royal-gunpowder",
    slug: "ceylon-royal-gunpowder",
    category: "tea",
    name: {
      en: "Ceylon Royal Gunpowder (Green)",
      fr: "Ceylan Royal Gunpowder (vert)",
    },
    origin: { en: "Sri Lanka · Ceylon", fr: "Sri Lanka · Ceylan" },
    tastingNotes: {
      en: ["Toasty", "Grassy", "Mineral"],
      fr: ["Grillé", "Herbacé", "Minéral"],
    },
    description: {
      en: "Green tea leaves hand-rolled into tight pellets that unfurl as they steep. Bold, toasty, and slightly smoky, with a clean mineral finish.",
      fr: "Feuilles de thé vert roulées à la main en petites perles qui se déploient à l'infusion. Franc, grillé et légèrement fumé, avec une finale minérale nette.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v2.jpg`,
    inStock: true,
  },
  {
    id: "darjeeling-mim",
    slug: "darjeeling-mim",
    category: "tea",
    name: { en: "Darjeeling (Mim FTGOP)", fr: "Darjeeling (Mim FTGOP)" },
    origin: { en: "India · Darjeeling", fr: "Inde · Darjeeling" },
    tastingNotes: {
      en: ["Muscatel", "Floral", "Stone fruit"],
      fr: ["Muscat", "Floral", "Fruit à noyau"],
    },
    description: {
      en: "The 'champagne of teas', from the famed Mim estate. Delicate and floral, with muscatel grape and stone-fruit notes.",
      fr: "Le « champagne des thés », du célèbre domaine Mim. Délicat et floral, avec des notes de raisin muscat et de fruits à noyau.",
    },
    priceCents: 1600,
    imageUrl: `${IMG}/Tea_v3.jpg`,
    inStock: true,
  },
  {
    id: "earl-grey",
    slug: "earl-grey",
    category: "tea",
    name: { en: "Earl Grey", fr: "Earl Grey" },
    origin: { en: "Black tea · Bergamot", fr: "Thé noir · Bergamote" },
    tastingNotes: {
      en: ["Bergamot", "Citrus", "Black tea"],
      fr: ["Bergamote", "Agrumes", "Thé noir"],
    },
    description: {
      en: "A black tea base scented with real bergamot oil. Bright, fragrant, and citrusy — the timeless afternoon cup.",
      fr: "Une base de thé noir parfumée à l'huile de bergamote véritable. Lumineux, parfumé et citronné — la tasse d'après-midi intemporelle.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v12.jpg`,
    inStock: true,
  },
  {
    id: "english-breakfast",
    slug: "english-breakfast",
    category: "tea",
    name: { en: "English Breakfast", fr: "English Breakfast" },
    origin: { en: "Black tea blend", fr: "Mélange de thé noir" },
    tastingNotes: {
      en: ["Malt", "Brisk", "Robust"],
      fr: ["Malt", "Vif", "Robuste"],
    },
    description: {
      en: "A full, robust blend of black teas — rich and brisk enough to wake you up and stand up to milk. The breakfast classic.",
      fr: "Un mélange de thés noirs plein et robuste — assez riche et vif pour vous réveiller et tenir tête au lait. Le classique du matin.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v8.jpg`,
    inStock: true,
  },
  {
    id: "formosa-oolong",
    slug: "formosa-oolong",
    category: "tea",
    name: { en: "Formosa Oolong", fr: "Oolong Formosa" },
    origin: { en: "Taiwan · Formosa", fr: "Taïwan · Formose" },
    tastingNotes: {
      en: ["Peach", "Honey", "Orchid"],
      fr: ["Pêche", "Miel", "Orchidée"],
    },
    description: {
      en: "A partially oxidized oolong from Taiwan. Smooth and rounded, with ripe peach, honey, and a soft floral aroma.",
      fr: "Un oolong partiellement oxydé de Taïwan. Lisse et rond, avec des notes de pêche mûre, de miel et un doux arôme floral.",
    },
    priceCents: 1600,
    imageUrl: `${IMG}/Tea_v9.jpg`,
    inStock: true,
  },
  {
    id: "irish-breakfast",
    slug: "irish-breakfast",
    category: "tea",
    name: { en: "Irish Breakfast", fr: "Irish Breakfast" },
    origin: { en: "Black tea blend", fr: "Mélange de thé noir" },
    tastingNotes: {
      en: ["Malt", "Bold", "Smooth"],
      fr: ["Malt", "Audacieux", "Lisse"],
    },
    description: {
      en: "Bolder and maltier than English Breakfast, built on Assam. Deep, full, and bracing — best with a splash of milk.",
      fr: "Plus corsé et plus malté que l'English Breakfast, bâti sur l'Assam. Profond, plein et tonifiant — meilleur avec un nuage de lait.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v10.jpg`,
    inStock: true,
  },
  {
    id: "jasmine-with-flowers",
    slug: "jasmine-with-flowers",
    category: "tea",
    name: {
      en: "Jasmine with Flowers (China, Green)",
      fr: "Jasmin aux fleurs (Chine, vert)",
    },
    origin: { en: "China", fr: "Chine" },
    tastingNotes: {
      en: ["Jasmine", "Floral", "Soft"],
      fr: ["Jasmin", "Floral", "Doux"],
    },
    description: {
      en: "Green tea scented with fresh jasmine blossoms. Fragrant, soft, and lightly sweet — soothing morning to night.",
      fr: "Thé vert parfumé aux fleurs de jasmin fraîches. Parfumé, doux et légèrement sucré — apaisant du matin au soir.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v14.jpg`,
    inStock: true,
  },
  {
    id: "keemun",
    slug: "keemun",
    category: "tea",
    name: { en: "Keemun", fr: "Keemun" },
    origin: { en: "China · Keemun", fr: "Chine · Keemun" },
    tastingNotes: {
      en: ["Cocoa", "Dried plum", "Wine"],
      fr: ["Cacao", "Prune séchée", "Vin"],
    },
    description: {
      en: "A celebrated Chinese black tea, naturally winey and smooth. Notes of cocoa and dried fruit with a gentle, almost sweet finish.",
      fr: "Un thé noir chinois réputé, naturellement vineux et lisse. Notes de cacao et de fruits séchés, avec une finale douce, presque sucrée.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v11.jpg`,
    inStock: true,
  },
  {
    id: "kenya-kambaa",
    slug: "kenya-kambaa",
    category: "tea",
    name: { en: "Kenya (Kambaa Estate)", fr: "Kenya (domaine Kambaa)" },
    origin: { en: "Kenya", fr: "Kenya" },
    tastingNotes: {
      en: ["Brisk", "Malt", "Citrus"],
      fr: ["Vif", "Malt", "Agrumes"],
    },
    description: {
      en: "A bright, brisk African black tea from the Kambaa estate. Full-bodied and lively, with a clean citrus edge.",
      fr: "Un thé noir africain vif et tonique du domaine Kambaa. Corsé et vivant, avec une touche d'agrumes nette.",
    },
    priceCents: 1300,
    imageUrl: `${IMG}/Tea_v16.jpg`,
    inStock: true,
  },
  {
    id: "lapsang-souchong",
    slug: "lapsang-souchong",
    category: "tea",
    name: { en: "Lapsang Souchong", fr: "Lapsang Souchong" },
    origin: { en: "China · Fujian", fr: "Chine · Fujian" },
    tastingNotes: {
      en: ["Pine smoke", "Cedar", "Dried fruit"],
      fr: ["Fumée de pin", "Cèdre", "Fruits séchés"],
    },
    description: {
      en: "Black tea smoke-dried over pinewood fires. Bold and unmistakably smoky, with a savoury, woodsy depth.",
      fr: "Thé noir séché à la fumée de feux de pin. Audacieux et indéniablement fumé, avec une profondeur boisée et savoureuse.",
    },
    priceCents: 1600,
    imageUrl: `${IMG}/Tea_v4.jpg`,
    inStock: true,
  },
  {
    id: "orange-pekoe",
    slug: "orange-pekoe",
    category: "tea",
    name: {
      en: "Orange Pekoe (Lover's Leap Estate)",
      fr: "Orange Pekoe (domaine Lover's Leap)",
    },
    origin: { en: "Sri Lanka · Ceylon", fr: "Sri Lanka · Ceylan" },
    tastingNotes: {
      en: ["Citrus", "Brisk", "Honey"],
      fr: ["Agrumes", "Vif", "Miel"],
    },
    description: {
      en: "A classic Ceylon black tea from the Lover's Leap estate. Bright, brisk, and clean, with a gentle citrus lift.",
      fr: "Un thé noir de Ceylan classique du domaine Lover's Leap. Lumineux, vif et net, avec une douce touche d'agrumes.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v5.jpg`,
    inStock: true,
  },
  {
    id: "sencha",
    slug: "sencha",
    category: "tea",
    name: { en: "Sencha (Japan, Green)", fr: "Sencha (Japon, vert)" },
    origin: { en: "Japan", fr: "Japon" },
    tastingNotes: {
      en: ["Grassy", "Marine", "Sweet"],
      fr: ["Herbacé", "Marin", "Sucré"],
    },
    description: {
      en: "Japan's everyday green tea, steamed to lock in its colour. Fresh and grassy, with a savoury umami sweetness.",
      fr: "Le thé vert quotidien du Japon, étuvé pour préserver sa couleur. Frais et herbacé, avec une douce sucrosité umami.",
    },
    priceCents: 1330,
    imageUrl: `${IMG}/Tea_v15.jpg`,
    inStock: true,
  },
  {
    id: "yunnan-fop",
    slug: "yunnan-fop",
    category: "tea",
    name: { en: "Yunnan (FOP)", fr: "Yunnan (FOP)" },
    origin: { en: "China · Yunnan", fr: "Chine · Yunnan" },
    tastingNotes: {
      en: ["Honey", "Malt", "Pepper"],
      fr: ["Miel", "Malt", "Poivre"],
    },
    description: {
      en: "A smooth, golden-tipped black tea from Yunnan. Mellow and naturally sweet, with honey, malt, and a peppery hint.",
      fr: "Un thé noir lisse aux pointes dorées du Yunnan. Moelleux et naturellement sucré, avec du miel, du malt et une pointe poivrée.",
    },
    priceCents: 1270,
    imageUrl: `${IMG}/Tea_v7.jpg`,
    inStock: true,
  },

  // ---------------------------------------------------------------------------
  // Gift baskets
  // ---------------------------------------------------------------------------
  {
    id: "goodies-galore",
    slug: "goodies-galore",
    category: "gift",
    name: { en: "Goodies Galore", fr: "Festin de gourmandises" },
    description: {
      en: "Our most generous gift basket, loaded with coffee, treats, and little luxuries. The grand gesture, ready to give.",
      fr: "Notre panier-cadeau le plus généreux, rempli de café, de gourmandises et de petits luxes. Le grand geste, prêt à offrir.",
    },
    priceCents: 12500,
    imageUrl: `${IMG_BASKETS}/WebCarmBaskPic3-scaled-e1574985923812.jpg`,
    featured: true,
    inStock: true,
  },
  {
    id: "nuts-about-coffee",
    slug: "nuts-about-coffee",
    category: "gift",
    name: { en: "Nuts About Coffee", fr: "Fou du café" },
    description: {
      en: "Coffee paired with nutty, chocolatey treats — a thoughtful gift for the caffeine lover in your life.",
      fr: "Du café accompagné de gourmandises aux noix et au chocolat — un cadeau attentionné pour l'amateur de caféine de votre entourage.",
    },
    priceCents: 7500,
    imageUrl: `${IMG_BASKETS}/WebCarmBaskPic2-scaled-e1574986016686.jpg`,
    inStock: true,
  },
  {
    id: "the-chefs-pantry",
    slug: "the-chefs-pantry",
    category: "gift",
    name: { en: "The Chef's Pantry", fr: "Le garde-manger du chef" },
    description: {
      en: "A curated basket of kitchen pleasures, anchored by great coffee. Built for the home cook who appreciates the good stuff.",
      fr: "Un panier soigné de plaisirs de cuisine, ancré par un excellent café. Pensé pour le cuisinier maison qui apprécie les bonnes choses.",
    },
    priceCents: 10000,
    imageUrl: `${IMG_BASKETS}/WebCarmBaskPic4-scaled-e1574985975184.jpg`,
    inStock: true,
  },
  {
    id: "the-coffee-collection",
    slug: "the-coffee-collection",
    category: "gift",
    name: { en: "The Coffee Collection", fr: "La collection café" },
    description: {
      en: "A sampler of our favourite coffees in one box — the easiest way to introduce someone to Café Gourmet.",
      fr: "Un assortiment de nos cafés préférés dans une seule boîte — la façon la plus simple d'initier quelqu'un à Café Gourmet.",
    },
    priceCents: 6000,
    imageUrl: `${IMG_BASKETS}/WebCarmBaskPic1-scaled.jpg`,
    featured: true,
    inStock: true,
  },
];
